---
# Apply common configuration to all hosts
- hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
  - common
  - puppet

- name: Install Foreman & Puppet Master
  hosts: foreman
  sudo: yes

  roles: 
  - foreman
  - puppet_master

- name: Run Reset Foreman DB Pw
  hosts: foreman
  sudo: yes
  post_tasks:
  - shell: foreman-rake permissions:reset
    register: dbpw_info
    when:  result|success
  
  - name: Printing your Foreman WebUI Credentials
    debug: msg="{{dbpw_info.stdout_lines}}"
    delegate_to: "{{ item }}"
    with_items: groups.foreman


- name: Install Puppet Agent
  hosts: agent
  sudo: yes

  roles:
  - puppet_agent

- name: Remove Firewalld settings
  hosts: all
  sudo: yes
  post_tasks: 
  - service: name=firewalld state=stopped enabled=no 



